### PR TITLE
timeouts resistance for the loadgen in the opbeans-rum project

### LINKED ISSUE #611: Fix the timeout issue with the opbeans RUM load generator
Currently if the page load takes longer than 10000 it throws an error and exists the process:

```
Error: wait(page load event) timed out after 10000ms
    at Timeout._onTimeout (/home/chrome/node_modules/chromeless/dist/src/util.js:180:32)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

We should either increase the timeout or catch and handle this error properly!

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Quick fix the timeouts in the loadgen

## Why is it important?

Ensure no environmental issues when the load of the page is a bit slow

## Related issues
Closes elastic/apm-integration-testing#611

### CODE REVIEW

File: docker/opbeans/rum/tasks.js [hunk 1]
```diff
@@ -10,30 +10,34 @@ function sleep(ms) {
...
+                        var i = Math.floor(Math.random() * links.length)
+                        return links[i].href
+                    } else {
+                        return baseUrl
+                    }
+                }, baseUrl);
+            console.log(url)
+            await sleep(8000 + Math.floor(Math.random() * 10000))
+        }
+    } catch (e){
```
Comment (kuisathaverat) [inline docker/opbeans/rum/tasks.js]: if the RUM agent is nor running for some reason, it would be stuck forever

Comment (kuisathaverat) [reply docker/opbeans/rum/tasks.js]: or when the stack is full

Comment (v1v) [reply docker/opbeans/rum/tasks.js]: If that's the case the timeout in the pipeline should kill it, not ideal, neither I know whether the use case of running the opbeans-rum without the RUM agent might be something which might happen.

File: docker/opbeans/rum/tasks.js [hunk 2]
```diff
@@ -10,30 +10,34 @@ function sleep(ms) {
...
+      run();
```
Comment (mdelapenya) [inline docker/opbeans/rum/tasks.js]: This is a recursion, right? If so, I'd recommend having a base case with an exit condition to avoid infinite loops.

I know that the pipeline will kill it, but just to make the code resilient and decoupled from the build tool

**Comment by v1v** [comment]
I didn't put enough context about the reason for using this approach, it's just a quick fix as discussed with the RUM team. As it seems a bit controversial, I'll hold this PR and work on using a kind of controlled loop to iterate a few times to avoid any kind of unexpected recurrency.

File: docker/opbeans/rum/tasks.js (hunk 1 above)
Comment (kuisathaverat) [reply docker/opbeans/rum/tasks.js]: I bet the time out is related to this line https://github.com/elastic/opbeans-frontend/blob/980651d5ca43124a686e9b1fd0e33483173375e5/src/components/ProductDetail/index.js#L8-L10

Comment (kuisathaverat) [reply docker/opbeans/rum/tasks.js]: I workaround this random fail in the Docker image by adding this config to the RUM agent https://github.com/elastic/apm-integration-testing/blob/master/docker/opbeans/frontend_nginx/rum-config.template

Comment (sqren) [reply docker/opbeans/rum/tasks.js]: Most of the opbeans apps add random failures to simulate real applications. 
I could be wrong but the random error seen here should only cause an uncaught exception.   It shouldn't cause Chrome to timeout like we see.

afaict the fix by @v1v works. You _could_ add a guard like:
```ts
} catch (e) {
  if (e.message.includes("timed out after")) {
    return run();
  }
  throw e;
}
```

File: docker/opbeans/rum/tasks.js [hunk 3]
```diff
@@ -37,4 +37,11 @@ async function run() {
...
 
-run().catch(console.error.bind(console))
+try {
+  run();
+} catch (e) {
+  if (e.message.includes("timed out after")) {
+    return run();
+  }
+  console.error.bind(console);
+}
```
Comment (sqren) [inline docker/opbeans/rum/tasks.js]: What you had before was better. This will only catch the first timeout. Additional timeouts will still make the process crash.

File: docker/opbeans/rum/tasks.js [hunk 4]
```diff
@@ -37,4 +37,11 @@ async function run() {
...
 }
 
-run().catch(console.error.bind(console))
+try {
+  run();
+} catch (e) {
+  if (e.message.includes("timed out after")) {
+    return run();
+  }
+  console.error.bind(console);
```
Comment (sqren) [inline docker/opbeans/rum/tasks.js]: This doesn't do anything. Probably what you meant is:
```js
console.error(e);
```

**Comment by sqren** [comment]
The following approach will make the process resistant to timeout errors (and other errors as well) without using recursion:

```
async function run() {
  const chromeless = new Chromeless({
    lauchChrome: true
  });

  for (;;) {
    try {
      url = await chromeless.goto(url).evaluate(baseUrl => {
        // activateLoadGeneration is defined in opbeans-frontend
        if (typeof window.activateLoadGeneration === "function") {
          console.log("Activating route change load generation");
          window.activateLoadGeneration();
        }

        var links = document.querySelectorAll('a[href^="/"]');
        if (links && links.length) {
          var i = Math.floor(Math.random() * links.length);
          return links[i].href;
        } else {
          return baseUrl;
        }
      }, baseUrl);
    } catch (e) {
      // this will catch the error, log it and let the process continue
      console.error(`Error occurred while evaluating ${url}:`, e);
    }
    console.log(url);
    await sleep(8000 + Math.floor(Math.random() * 10000));
  }
}

run().catch(console.error.bind(console));
```

File: docker/opbeans/rum/tasks.js (hunk 3 above)
Comment (v1v) [reply docker/opbeans/rum/tasks.js]: There was a discussion earlier to avoid using the recursion as that particular implementation could potentially end as an infinite loop, refers to:
- https://github.com/elastic/apm-integration-testing/pull/664#discussion_r345300191
- https://github.com/elastic/apm-integration-testing/pull/664#discussion_r345293432

No strong opinion about what's the best strategy though, probably I misunderstood what you meant in your comment: https://github.com/elastic/apm-integration-testing/pull/664#discussion_r346056629

@kuisathaverat  and @mdelapenya what're your thoughts if we keep the first approach with the suggested improvement : https://github.com/elastic/apm-integration-testing/pull/664#discussion_r346056629 ?

Comment (kuisathaverat) [reply docker/opbeans/rum/tasks.js]: I'll buy the Soren solution https://github.com/elastic/apm-integration-testing/pull/664#issuecomment-553860528 😃

Comment (kuisathaverat) [reply docker/opbeans/rum/tasks.js]: BTW https://twitter.com/johnwilander/status/1176457013305303040?lang=en
